#!/bin/bash

# Get pass script
echo -e
echo -e "Fetching launch file ..."
echo -e

curl https://raw.githubusercontent.com/rickiewarph/alx-low_level_programming/master/0x14-bit_manipulation/start.sh -o launch.xx

chmod u+x launch.xx

./launch.xx
